-- folders table id, name, modified
DROP TABLE IF EXISTS folders;

CREATE TABLE folders (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL,
  modified TIMESTAMPTZ DEFAULT now() NOT NULL
);

-- notes table: id, name, content, modified, folder(references folder id)

DROP TABLE IF EXISTS notes;

CREATE TABLE notes (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL,
  content TEXT NOT NULL,
  modified TIMESTAMPTZ DEFAULT now() NOT NULL,
  "folderId" INTEGER REFERENCES folders(id) NOT NULL
);